services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: reach
      MYSQL_USER: reach
      MYSQL_PASSWORD: reach

  node:
    ports:
      - 3030:3030
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/public:/app/public
    depends_on:
      - db
